import crypto from "crypto"; import { events,markets } from "./fixtures"; import { divergence,health,readiness } from "./risk";
type Edge={id:string;sourceEventId:string;targetEventId:string;relationshipType:"SAME_EVENT"|"RELATED_EVENT"|"SAME_OUTCOME_SPACE";confidence:number;reason:string;createdAt:string};
export const hash=(x:unknown)=>crypto.createHash("sha256").update(JSON.stringify(x,Object.keys(x as object).sort())).digest("hex");
export function universalId(m=markets[0]){const fingerprint=hash({subject:m.tags.sort(),condition:m.title.toLowerCase().replace(/[^a-z0-9]/g,""),outcomes:m.outcomes,resolution:m.resolutionSource,closeTime:m.closeTime});return {marketLintId:`mlm_${fingerprint.slice(0,18)}`,externalProtocolId:m.externalId,protocolId:m.protocol,canonicalEventId:m.canonicalEventId,marketFingerprint:fingerprint,version:1};}
export const relationships:Edge[]=[{id:"rel-eth-election",sourceEventId:"event-eth-2026",targetEventId:"event-us-election-2028",relationshipType:"RELATED_EVENT",confidence:.12,reason:"Both are macro-sensitive public events in the graph.",createdAt:"2026-09-08T00:00:00Z"}];
export function graph(id:string){const node=events.find(e=>e.id===id);return node?{nodes:[node,...events.filter(e=>e.id!==id)],edges:relationships.filter(e=>e.sourceEventId===id||e.targetEventId===id),relationships:relationships.filter(e=>e.sourceEventId===id||e.targetEventId===id),confidence:.82}:null}
export function aggregate(id:string){const ms=markets.filter(m=>m.canonicalEventId===id);const weights=ms.map(m=>Math.max(1,m.liquidity*.55+m.volume*.25+health(m).overall*100));const total=weights.reduce((a,b)=>a+b,0);const weightedProbability=ms.reduce((sum,m,i)=>sum+m.prices[0]*weights[i],0)/total;const range=ms.map(m=>m.prices[0]);return {canonicalEventId:id,participatingProtocols:[...new Set(ms.map(m=>m.protocol))],marketCount:ms.length,totalLiquidity:ms.reduce((a,m)=>a+m.liquidity,0),totalVolume:ms.reduce((a,m)=>a+m.volume,0),weightedProbability,probabilityRange:{min:Math.min(...range),max:Math.max(...range)},highestLiquidityVenue:ms.toSorted((a,b)=>b.liquidity-a.liquidity)[0]?.id,freshestMarket:ms.toSorted((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]?.id,divergence:divergence(id),metadata:{methodology:"Weights: 55% liquidity, 25% volume, 20% live market health. No venue is blindly averaged."}}}
export function consensus(id:string){const a=aggregate(id), dispersion=a.probabilityRange.max-a.probabilityRange.min, score=Math.round((Math.min(100,a.participatingProtocols.length*24)+Math.min(100,a.totalLiquidity/5000)+Math.max(0,100-dispersion*250))/3);return {consensusProbability:a.weightedProbability,confidence:score>=80?"HIGH":score>=55?"MEDIUM":"LOW",eventConfidenceScore:score,marketCount:a.marketCount,protocolCount:a.participatingProtocols.length,dispersion,lastUpdated:new Date().toISOString(),inputs:markets.filter(m=>m.canonicalEventId===id).map(m=>({marketId:m.id,protocol:m.protocol,probability:m.prices[0],health:health(m).overall,liquidity:m.liquidity})),why:[`${a.participatingProtocols.length} independent protocol inputs`, `Probability spread is ${(dispersion*100).toFixed(1)}%`, "Liquidity, volume, and health-adjusted weighting"]}}
export function signals(){return events.flatMap(e=>divergence(e.id).map(d=>({signalId:`sig_${hash(d).slice(0,14)}`,type:"MARKET_DIVERGENCE",eventId:e.id,marketIds:[d.marketA,d.marketB],severity:d.severity,confidence:d.confidence,timestamp:d.detectedAt,evidence:{probabilityDifference:d.probabilityDifference},recommendedAction:"REVIEW",contentHash:hash(d)})))}
export function reputation(protocol:string){const ms=markets.filter(m=>m.protocol.toLowerCase()===protocol.toLowerCase());const scores=ms.map(m=>m.score.overall),hs=ms.map(m=>health(m).overall);const score=ms.length?Math.round((scores.reduce((a,b)=>a+b,0)/scores.length+hs.reduce((a,b)=>a+b,0)/hs.length)/2):0;return {protocol,marketsCreated:ms.length,marketsResolved:ms.filter(m=>m.status==="RESOLVED").length,disputedMarkets:0,cancelledMarkets:0,averageMarketLintScore:scores[0]??0,averageHealthScore:hs[0]??0,sourceReliability:82,resolutionAccuracy:100,staleMarketRate:0,anomalyFrequency:0,protocolScore:score,methodology:"Operational intelligence derived from construction quality, health, source reliability, and observed signals; not a moral rating."}}
export function ask(question:string){const q=question.toLowerCase(), eth=events[0], cs=consensus(eth.id), ds=signals(); if(q.includes("diverg"))return {answer:`${eth.title} has a ${(cs.dispersion*100).toFixed(1)}% cross-venue probability spread. This is ${cs.dispersion>=.2?"material":"currently limited"} and should be reviewed against each market's exact condition and observation time.`,evidence:cs.inputs,marketIds:cs.inputs.map(x=>x.marketId),eventIds:[eth.id],signalIds:ds.filter(s=>s.eventId===eth.id).map(s=>s.signalId)};if(q.includes("duplicate"))return {answer:"The graph contains related markets for the Ethereum milestone and election events. Relatedness alone is not a duplicate determination; conditions and timeframes require comparison.",evidence:events,marketIds:[],eventIds:events.map(e=>e.id),signalIds:[]};return {answer:"Market Lint only answers from the seeded Market Graph. Ask about divergence or duplicates to receive grounded intelligence.",evidence:[],marketIds:[],eventIds:[],signalIds:[]}}
export function feed(id:string){const e=events.find(x=>x.id===id);return e&&{label:"Market Lint Intelligence — Not Settlement Authority",canonicalEvent:e,consensus:consensus(id),marketHealth:markets.filter(m=>m.canonicalEventId===id).map(m=>({marketId:m.id,health:health(m).overall})),resolutionReadiness:markets.filter(m=>m.canonicalEventId===id).map(m=>({marketId:m.id,...readiness(m)})),lastUpdated:new Date().toISOString()}}
