import crypto from "crypto"; import { markets } from "./fixtures"; import { Market } from "./market-types"; import { analyze } from "./graph";
export type Lifecycle="DRAFT"|"PRE_LAUNCH"|"ACTIVE"|"CLOSING"|"AWAITING_RESOLUTION"|"RESOLVED"|"DISPUTED"|"CANCELLED"; export type Severity="LOW"|"MEDIUM"|"HIGH"|"CRITICAL"; export type Signal={id:string;type:string;severity:Severity;confidence:number;explanation:string;evidence:Record<string,number|string>;detectedAt:string}; export type Snapshot={timestamp:string;probability:number;liquidity:number;volume:number};
export const riskConfig={probabilityMoveThreshold:.25,lowVolumeThreshold:10000,liquidityExitThreshold:.3,divergenceThreshold:.2}; const state=new Map<string,{lifecycle:Lifecycle;snapshots:Snapshot[];signals:Signal[]}>();
export function lifecycleFor(m:Market):Lifecycle { if(m.status==="RESOLVED")return "RESOLVED"; if(m.status==="CLOSED")return "AWAITING_RESOLUTION"; return "ACTIVE" }
export function watch(m:Market){if(!state.has(m.id))state.set(m.id,{lifecycle:lifecycleFor(m),snapshots:[{timestamp:new Date().toISOString(),probability:m.prices[0],liquidity:m.liquidity,volume:m.volume}],signals:[]});return state.get(m.id)!}
function signal(type:string,severity:Severity,confidence:number,explanation:string,evidence:Record<string,number|string>):Signal{return{id:crypto.randomUUID(),type,severity,confidence,explanation,evidence,detectedAt:new Date().toISOString()}}
export function evaluate(m:Market,next:Omit<Snapshot,"timestamp">){const w=watch(m),previous=w.snapshots.at(-1)!;const signals:Signal[]=[];const move=Math.abs(next.probability-previous.probability); if(move>=riskConfig.probabilityMoveThreshold)signals.push(signal("PRICE_ANOMALY",move>.4?"CRITICAL":"HIGH",.96,"Probability moved beyond the configured threshold in one observation.",{previousProbability:previous.probability,currentProbability:next.probability,move})); if(next.liquidity<previous.liquidity*(1-riskConfig.liquidityExitThreshold))signals.push(signal("LIQUIDITY_RISK","HIGH",.94,"Liquidity withdrew beyond the configured exit threshold.",{previousLiquidity:previous.liquidity,currentLiquidity:next.liquidity})); if(next.volume-previous.volume>100000&&move<.02)signals.push(signal("VOLUME_ANOMALY","MEDIUM",.86,"High volume printed with little price discovery.",{volumeDelta:next.volume-previous.volume,move})); const snapshot={...next,timestamp:new Date().toISOString()};w.snapshots.push(snapshot);w.signals.push(...signals);return signals}
export function health(m:Market){const w=watch(m), latest=w.snapshots.at(-1)!, penalty=w.signals.slice(-5).reduce((n,s)=>n+({LOW:4,MEDIUM:10,HIGH:20,CRITICAL:35}[s.severity]),0);const components={liquidityHealth:Math.min(100,Math.round(latest.liquidity/1500)),tradingActivity:Math.min(100,Math.round(latest.volume/5000)),priceStability:Math.max(0,100-penalty),crossMarketConsistency:78,resolutionReadiness:readiness(m).status==="READY"?90:55,sourceHealth:sourceCheck(m.resolutionSource).reliabilityScore,manipulationSignals:Math.max(0,100-penalty)};return {overall:Math.round(Object.values(components).reduce((a,b)=>a+b,0)/7),components,signals:w.signals.slice(-10)} }
export function divergence(eventId:string){const related=markets.filter(m=>m.canonicalEventId===eventId);return related.flatMap((a,i)=>related.slice(i+1).map(b=>{const difference=Math.abs(a.prices[0]-b.prices[0]);return {canonicalEventId:eventId,marketA:a.id,marketB:b.id,probabilityDifference:difference,liquidityDifference:Math.abs(a.liquidity-b.liquidity),confidence:.88,severity:difference>=riskConfig.divergenceThreshold?"HIGH":"LOW",detectedAt:new Date().toISOString()}})).filter(x=>x.severity!=="LOW")}
export function sourceCheck(url:string){let domain="";try{domain=new URL(url.startsWith("http")?url:`https://${url}`).hostname.toLowerCase()}catch{} const blocked=/^(localhost|127\.|0\.|10\.|192\.168\.|169\.254\.|\[?::1)/.test(domain); return {url,domain,type:domain.includes("gov")?"OFFICIAL_GOVERNMENT":domain.includes("coinbase")?"EXCHANGE":"CUSTOM",reliabilityScore:blocked||!domain?20:domain.includes("gov")?92:domain.includes("coinbase")?84:58,availability:!blocked&&!!domain,lastCheckedAt:new Date().toISOString(),historicalUsage:blocked?0:12,disputeCount:blocked?2:0,blocked}; }
export function readiness(m:Market){const source=sourceCheck(m.resolutionSource);if(!source.availability)return {status:"HIGH_DISPUTE_RISK",reasons:["Resolution source is invalid or points to a blocked/private destination."]};if(!m.resolutionTime)return {status:"REVIEW_REQUIRED",reasons:["No resolution time is defined."]};return {status:"READY",reasons:["Resolution source is available and the fixture has a deterministic UTC close condition."]}}
export function guard(input:{title:string;description?:string;outcomes?:string[];resolutionSource?:string;closeTime?:string}){const result=analyze({title:input.title,description:input.description,outcomes:input.outcomes,resolution:input.closeTime,source:input.resolutionSource});const source=sourceCheck(input.resolutionSource??"");const warnings:string[]=[];if(result.duplicateRisk!=="LOW")warnings.push("Potentially overlapping market found; review the exact condition and observation window.");if(!source.availability)warnings.push("Resolution source is unavailable, invalid, or unsafe to fetch.");const decision=!source.availability||result.score.overall<45?"BLOCK":result.duplicateRisk==="HIGH"||result.score.overall<75?"REVIEW":"ALLOW";return {decision,marketLintScore:result.score.overall,duplicateRisk:result.duplicateRisk,ambiguityRisk:result.score.settlementAmbiguity<65?"HIGH":"LOW",resolutionRisk:source.reliabilityScore<60?"HIGH":"LOW",manipulationRisk:result.score.manipulationRisk<70?"MEDIUM":"LOW",canonicalEvent:result.canonicalEvent,warnings,suggestions:["Specify a primary resolution source and source-precedence rule.","State a UTC observation deadline."],reasons:decision==="ALLOW"?["Construction checks passed configured thresholds."]:warnings};}
export function webhookSignature(secret:string,payload:string){return crypto.createHmac("sha256",secret).update(payload).digest("hex")}
